### ISSUE TITLE
[提案] 執筆者の呼称について

### ISSUE THREAD

**Issue by thinca** [vim-jp/ekiden#106]
より駅伝感を出すため、執筆者の呼称を以下のように統一することを提案します。

- runner
  - `content.json` の `author` や https://github.com/vim-jp/ekiden/pull/101 で追加されるページの URL など、内部的な部分、英数字のみの部分に使用
- 走者
  - ユーザーに見える場面で使用
  - 現時点で適用箇所があるかちょっとわからない

しばらく反応を見て、大きな反対がなければ全体的に変更する PR を作ります(誰か作ってくれてもよいです)。

**Comment by ArcCosine** [comment]
runner→良さそう
走者→第n走者みたいに表示しても良さそうです。
アーカイブページや、トップページに番号をcontent.jsonからのカウントを使えば出来そう。

いずれにせよ、
![LGTM](https://images.lgtmgen.org/b3779499-a569-46a7-8cf7-eff3802931d5)
です。
