### ISSUE TITLE
2023-08-02

### ISSUE THREAD

**Issue by jack-a129** [vim-jp/ekiden#129]
### 執筆者名

浅倉有人

### 記事タイトル

Vimっぽいな feat.初音zenn

### 記事 URL

https://zenn.dev/asakuraarihito/articles/0357afbdf4abfc

**Comment by thinca** [comment]
@jack-a129 すでに記事が公開されてしまっていないでしょうか? 当日になったら公開するようにいて頂けると助かります :pray:

**Comment by thinca** [comment]
@jack-a129 こちらいかがでしょう？
