### ISSUE TITLE
OGP をいい感じにする

### ISSUE THREAD

**Issue by monaqa** [vim-jp/ekiden#206]
たとえば現状、 Zenn でリンクを貼ると以下のような感じになるっぽいです。
もうちょっとカッコよくてもよい気がする（特に画像のところは別のなにかに差し替えたい）

<img width="721" alt="image" src="https://github.com/vim-jp/ekiden/assets/48883418/e8432703-d011-431a-bb48-1bc3a91d2556">

**Comment by peacock0803sz** [comment]
一旦vim-jpのfaviconとog:descriptionを設定すればマシになりますかね?
全体で統一でもog:imageはあった方がいいと思いますが、とりあえずの対応として

**Comment by peacock0803sz** [comment]
あーこれ、画像ナシの時にFaviconへFailbackするかは貼りつけ先次第ですね。やはり作るべきか

**Comment by peacock0803sz** [comment]
画像作ってみました。シンプルと説明的な文字入りの2種類あるので、こんな感じで良ければ選んでください
文字部分をもう少し弄るのも可能です

## type-a (シンプル)

![type-a](https://github.com/vim-jp/ekiden/assets/33555487/1948d26e-6c36-43e2-9a23-8288fd4a34e3)

## type-b (文字入り)

![type-b](https://github.com/vim-jp/ekiden/assets/33555487/48119914-8eee-4aec-a8ee-8f4530c0da34)

**Comment by kuuote** [comment]
aの方がシュッとしているけど、OGPなら説明的なbの方がよさそうな気がします

**Comment by kuuote** [comment]
それとも解説はdescriptionの方がいいですかね？

**Comment by monaqa** [comment]
ありがとうございます！
description があるなら説明はそちらに寄せるほうが良さそうな気もしますね。

**Comment by peacock0803sz** [comment]
OGPだけ見える場合もあるので、端的に説明を入れてみたのがbの案ですね

**Comment by kuuote** [comment]
そういう事情があるならbがいいかもですね

**Comment by peacock0803sz** [comment]
b案で主要ソーシャルメディアに掲載したときの挙動はこんな風になります

![CleanShot 2023-11-26 at 20 30 28](https://github.com/vim-jp/ekiden/assets/33555487/6b299a75-9c66-46eb-8c35-2c7e03a01dea)

**Comment by kuuote** [comment]
良さそう

**Comment by monaqa** [comment]
どちらでも良いと思います！
