### ISSUE TITLE
GHA からの medium.com の記事の確認に失敗する

### ISSUE THREAD

**Issue by thinca** [vim-jp/ekiden#219]
- https://github.com/vim-jp/ekiden/issues/119
- https://github.com/vim-jp/ekiden/issues/180
- https://github.com/vim-jp/ekiden/issues/199
- https://github.com/vim-jp/ekiden/issues/204

なぜか GHA からの投稿確認の際に 403 になってしまうが、実際に Web ブラウザ等からアクセスしてみると 200 になる。
アクセス元によって弾いたり等している？

**Comment by satorunooshie** [comment]
https://github.com/vim-jp/ekiden/issues/283 では 403 にならず正常に issue close されたので再発しないようであれば閉じて良いかもしれません

**Comment by thinca** [comment]
ありがとうございます。一旦閉じます。
再発する場合は Reopen しようと思います。
