### ISSUE TITLE
リポジトリのメンテナを明示する

### ISSUE THREAD

**Issue by peacock0803sz** [vim-jp/ekiden#228]
特に義務は発生しないが、機能実装や修正の際にフローが定まっている必要がある

**Comment by peacock0803sz** [comment]
ステークホルダを明らかにして開発を進めやすくする目的もある

**Comment by peacock0803sz** [comment]
関係者と思わしき人物を召喚しておきます @monaqa @thinca

**Comment by peacock0803sz** [comment]
CODEOWNERSも設定したいなあ

**Comment by thinca** [comment]
関係者です。どこに明示されているとわかりやすいですかね？
(脇道だけど、コアメンテナが誰なのかわからんのって GitHub の全リポジトリに共通で言える問題ですよねぇ)

**Comment by peacock0803sz** [comment]
書くならREADMEかCODEOWNERSですかねえ。後者はルールが書ける
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

**Comment by peacock0803sz** [comment]
@thinca @monaqa とりあえずREADME/CODEONWERS設定するPR作ってみます
