### ISSUE TITLE
トップページから Vim 駅伝のページにリンクをする

### ISSUE THREAD

**Issue by thinca** [vim-jp/ekiden#27]
実際の作業は↓のリポジトリでやる必要があります。

https://github.com/vim-jp/vim-jp.github.io

追加場所は、右のサイドバーあたり? 他に意見あればください。

**Comment by kuuote** [comment]
ですね、Slackとか案内している部分にあったらいいと思います。

**Comment by staticWagomU** [comment]
[vim-jp.github.io](https://github.com/vim-jp/vim-jp.github.io)にてIssue起票いたしました。
