### ISSUE TITLE
a タグのネストをなくす

### ISSUE THREAD

**Issue by monaqa** [vim-jp/ekiden#338]
現在記事へのリンクの中の一部が走者へのリンクとなっており、UI 上あまり直感的でないので改善したい。

詳細: https://github.com/vim-jp/ekiden/pull/337#discussion_r1517221646

**Comment by mikoto2000** [comment]
@monaqa 
コミット 62187f1 でネストが解消されているようです。

**Comment by monaqa** [comment]
ご指摘ありがとうございます、解消されてましたね。クローズします。
