### ISSUE TITLE
キャンセルの条件を変更する

### ISSUE THREAD

**Issue by kyoh86** [vim-jp/ekiden#409]
## 背景

IssueをCloseした際に条件を満たした場合はcontents.jsonから該当記事のエントリを削除する処理が実行されている。

https://github.com/vim-jp/ekiden/blob/26c70f17bdf7f5c3bb14cf850c092a5256aa153b/.github/workflows/update-article.yml#L32-L39

https://github.com/vim-jp/ekiden/blob/26c70f17bdf7f5c3bb14cf850c092a5256aa153b/scripts/update-article.ts

現在の正常系キャンセルの条件は

- 記事URLが書かれていないこと
- かつ Closeの操作が `Close as not planned` で行われていること

となっているが、見直しても良さそう。

## 経緯

- 同一日付の記事投稿に関するIssue起票が重複 (#400, #401) した
- 片方を取り下げるために @kyoh86 が #400 をCloseしたが、 `Closed as completed`で閉じてしまった
- Close操作のデフォルトが as completed であることもあり、この条件に気づいてキャンセルするのが少し難しい、という理解
- 案内を出すようにした（ #408 ）が、fool-proofで考えると条件を見直しても良さそう

## 案

@kyoh86 : IssueのClose時に次の **いずれか** を満たせばキャンセル扱いでよいのではないか

1. 記事URLがない
2. 投稿予定日付（JST）より前
3. `Close as not planned`

**Comment by thinca** [comment]
すでに正常に公開済みの Issue をキャンセル条件を満たすように更新した場合、どうするのがいいですかね？

**Comment by thinca** [comment]
「すでに正常に公開済みかどうか」を判断する術がないので、一律でキャンセル(JSON からエントリーを削除する)で良い気がしてきた。

**Comment by kyoh86** [comment]
公開済みかどうかは判断しようがない（厳密に定義されたインターネットならあるけど、そんなものはない）ので、私としてはIssue bodyに書いた「案」のいずれかを満たせばキャンセル、それ以外は特になにもしない（キャンセルでもなんでもない）と考えています。
