### ISSUE TITLE
Duplicate runs of checking workflow by `check-article.yml`

### ISSUE THREAD

**Issue by peacock0803sz** [vim-jp/ekiden#433]
#411, #312, #413, #420 で再現している模様、おそらく#411 より前は発生していないと思われる。

https://github.com/vim-jp/ekiden/blob/ee84d80e45952a476dccadca5095ddb9cc32408c/.github/workflows/check-article.yml#L8-L10

このあたり↑で2回発火しているのは良いはず。

https://github.com/vim-jp/ekiden/blob/ee84d80e45952a476dccadca5095ddb9cc32408c/.github/workflows/check-article.yml#L69-L73

本当の原因はこっち↑の `if` が動作していないからか?

## Screenshots in Reproductions (#420)

![CleanShot 2024-05-23 at 14 19 15](https://github.com/vim-jp/ekiden/assets/33555487/a9285cf0-ff46-47b7-956c-fb5e71e808ec)

## Workflow Runs (#420)

* <https://github.com/vim-jp/ekiden/actions/runs/9183434750/job/25254138005>
* <https://github.com/vim-jp/ekiden/actions/runs/9193644513/job/25285185451>

**Comment by peacock0803sz** [comment]
share: @thinca

**Comment by mityu** [comment]
> おそらくhttps://github.com/vim-jp/ekiden/issues/411 より前は発生していないと思われる。

「`@...` 投稿を確認できました〜」が2回投稿される、という話であれば割と前から発生していて、多分 https://github.com/vim-jp/ekiden/issues/272 この辺りが境目なんじゃないかなーと。

**Comment by peacock0803sz** [comment]
> > おそらく#411 より前は発生していないと思われる。
> 
> 「`@...` 投稿を確認できました〜」が2回投稿される、という話であれば割と前から発生していて、多分 #272 この辺りが境目なんじゃないかなーと。

@mityu おー、ほんとだ。確認ありがとうございます!!

**Comment by k-takata** [comment]
https://github.com/vim-jp/ekiden/commit/c83a2ca03d06a234f90b5595d587acbe884667d2
completed で close されている場合、そのまま残りの処理を行うので、2回投稿されるのではないかと。
