### ISSUE TITLE
「Vim 駅伝について」の説明を追加する

### ISSUE THREAD

**Issue by thinca** [vim-jp/ekiden#48]
Vim 駅伝とは何か、について説明するページを追加し、トップページからリンクする。
内容についても検討する必要がある。

もし 1,2 行で済むようであれば、ページを分けずにトップページに直接書いてしまってもよい。

**Comment by monaqa** [comment]
ページ構成については #19 でも議論しているので、そちらにもコメントいただければ！
（ページ構成についての議論は別 issue 切っても良かったかも？）

**Comment by kyoh86** [comment]
誰かが素案を出してみんなで殴るスタイルじゃないと議論が前に進まなさそうなので、文字通りたたき台。好きに殴ってくれ！！

### Vim駅伝とは

Vim駅伝とは、Vimmerたちが技術的なコンテンツを持ち寄り、リレー形式で記事をリンクする営みです。
小さなノウハウ、ちょっとした気づき、作ったプラグイン、開発の苦労話など、様々な話を集めています。

### 他に載せるべき物は

- 注意事項
    - 個人攻撃のためのものではない
    - 喧嘩しない
    - 載せちゃいけない物
        - 宗教、政治などテクノロジーから遠く離れた話題？
        - 社外秘情報など出さないように：インターネットリテラシーまでここで言及する必要はないか？
- 書き方
    - 当日書いてないと誰かに奪われるかも
    - よしなに譲り合って書こう

**Comment by kyoh86** [comment]
書き方の内容は #49 でOK

**Comment by monaqa** [comment]
良いと思います！

vim-jp には非 Vimmer もいるので、「Vimmerたちが」のところは「Vimmer を中心に」などとしても良いかもですね。（なにをもって Vimmer と呼ぶかにもよる？）

注意事項について、よりしっかり運営するなら、将来的にはコミュニティの Code of conduct みたいなのを作ってそっちでしっかり規定するのがいいのでしょうが、ひとまず今は記事内容に対する注意事項だけで良いと思います。

**Comment by kyoh86** [comment]
> 「Vimmerたちが」のところは「Vimmer を中心に」などとしても良い

Vimmer（概念）に慣れすぎてましたが、確かにそうですね。その方が良さそうです！

**Comment by monaqa** [comment]
#52 で概要を追加したので、こちらクローズしてしまって良いでしょうか？ @thinca
