### ISSUE TITLE
Vim 駅伝に参加する方法の説明を追加する

### ISSUE THREAD

**Issue by thinca** [vim-jp/ekiden#49]
Issue の新規作成のテンプレートからリンクしたいので、独立したページだとベター。
構成によっては about ページと一緒でも問題はない。

**Comment by monaqa** [comment]
ページ構成については #19 でも議論しているので、そちらにもコメントいただければ！
（ページ構成についての議論は別 issue 切っても良かったかも？）

**Comment by peacock0803sz** [comment]
忘れないようにメモ。以下も明記する必要がありそうです
https://github.com/vim-jp/ekiden/pull/509#issuecomment-2285370158

* 期日まで記事は公開しない方が望ましい
* Issueは自動クローズされるのでエントリした人が操作しなくてOK

**Comment by kyoh86** [comment]
ざっくりとした流れが分かりにくい構造になってるのかも？
https://vim-jp.slack.com/archives/C04N5HV5YTY/p1724571529056389

**Comment by thinca** [comment]
https://github.com/vim-jp/ekiden/pull/724 で [アバウトページ](https://vim-jp.org/ekiden/about/) が追加されたので、一旦完了とします。
