### ISSUE TITLE
ライセンスを決める

### ISSUE THREAD

**Issue by thinca** [vim-jp/ekiden#50]
勢いで作ったのでライセンスがまだ決まってませんでした。

- [x] ライセンスを決める
- [x] LICENSE ファイルを置く
- [ ] Web ページ内にライセンスを記載する

**Comment by kuuote** [comment]
jsonデータ以外はMITやzlibのような緩いライセンスでいい気がします。データは何にしたらいいのかが分からないですね…

**Comment by kuuote** [comment]
All rights revsersedにしておくのがいいのだろうか

**Comment by kyoh86** [comment]
CC系の方がメディア跨いだときにやりやすいみたいな話なかったでしたっけ。
各々のメディアに載せてるので、内容のorigin rightだけに踏み込むものにしておく必要がありそう。

**Comment by kyoh86** [comment]
や、考えてみると「単なるリンク集」なので、rightはタイトルくらいか。
適用範囲だけきちんと明示しておくのが大事そう

**Comment by kuuote** [comment]
リンクのデータは各著者の物なので流用しないでくださいって書いておくのがいいのかな
