### ISSUE TITLE
2024-08-16

### ISSUE THREAD

**Issue by fs0414** [vim-jp/ekiden#527]
### 執筆者名

fujitani sora

### 記事タイトル

NeoVimに閉じ籠る為のToggletermとGit, DockerのTUI

### 記事 URL

https://zenn.dev/toridori/articles/5ac8d3618c9009

**Comment by thinca** [comment]
@fs0414 Issue のクローズは参加キャンセルを意味します。
もし意図していない場合は、再オープンしてください。
また、記事は予定日になってから公開してもらえると助かります :pray:

**Comment by fs0414** [comment]
@thinca
ご確認いただきありがとうございます🙏🙇 
下記2点完了しています。
- Issueの再オープン
- 記事を一旦非公開にする

**Comment by thinca** [comment]
ご対応ありがとうございます！:pray:
