### ISSUE TITLE
2024-08-21【toridori.ts】NeoVimでprisma-language-serverを適用する手順

### ISSUE THREAD

**Issue by fs0414** [vim-jp/ekiden#530]
### 執筆者名

fs0414

### 記事タイトル

【toridori.ts】NeoVimでprisma-language-serverを適用する手順

**Comment by thinca** [comment]
FYI: 別の日で登録したい場合、Issue のタイトルの日付を直接変更しても大丈夫です。月水金のいずれかの曜日である必要があります。
新しく Issue を開くのでも問題ありません。
