### ISSUE TITLE
トップページの空き枠を確保する

### ISSUE THREAD

**Issue by kyoh86** [vim-jp/ekiden#742]
> 最近駅伝に登録してくれる人が多いですねえ。とてもありがたい。
もうすぐ1ヶ月先まで全部埋まっちゃうので、駅伝ページで表示される先を伸ばしたほうがいいかも？

という声が聞かれました。事実として11月30日現在で、見かけ上の空き枠は1日となっています。
<img src="https://github.com/user-attachments/assets/0bf58fbc-9aad-4b92-917d-622ab8310495" width="300" />

**Comment by kyoh86** [comment]
現在の日付選定の仕様がよく分からない。
アルゴリズム的に決まっているのはArticles.astroから読み取れるのだが、これの「意図」が分からないのでどうしたものか…。
https://github.com/vim-jp/ekiden/blob/324ce4cba7678fe692a5afccd41bd7e2d0e91285/src/components/Articles.astro

**Comment by kyoh86** [comment]
とりあえず改善としては「空き枠が最低でもN個表示される状態にする」で良いと思う。固定のMヶ月で表示しに行くのは筋が悪いというか。

**Comment by kyoh86** [comment]
現行仕様の意図は、辿っていくとこういうこと。

https://github.com/vim-jp/ekiden/blame/9bc629a4960fcef7179a2777dfe6fb88fc217ee7/src/components/Calendar.tsx

```
function registrationLinkDisplayDates(today: dayjs.Dayjs): string[] {
  const dates = [];
  // 特定の条件を満たす日のみリストに加える
  for (let i = 0; i < REGISTRATION_LINK_DISPLAY_DAYS; i++) {
    const date = today.add(i, "day");
    // 月、水、金
    if ([1, 3, 5].includes(date.get("day"))) {
      dates.push(date.format("YYYY-MM-DD"));
    }
  }
  return dates;
}```

Calendarを消したときにこの「意図」が消えてしまったのか。

**Comment by kyoh86** [comment]
で、それに関するテストがないのね。なんとまあ。

**Comment by kyoh86** [comment]
単純な日付生成の仕組みがAstroの中に入ってしまってるの、邪魔くさいな。src/libに日付生成用のアルゴリズムがあれば小さくテストを書ける気がする。新しいアルゴリズムで同じ基準のgeneratorを置いてそちらに乗り換えるというスタイルで進めるか。

**Comment by kyoh86** [comment]
え、jestすら入ってないの？しんど

**Comment by kyoh86** [comment]
ユニットテストはVitest使えってのがAstro公式見解っぽい。
https://docs.astro.build/ja/guides/testing/#vitest
入れておこう。

**Comment by monaqa** [comment]
> src/libに日付生成用のアルゴリズムがあれば小さくテストを書ける気がする。

:yosasou:
